sudo: required
language: node_js
addons:
  chrome: stable
before_install: # if "install" is overridden
  # Repo for Yarn
  - npm install yarn -g
cache:
  yarn: true
notifications:
  email: false
node_js:
  - "10"
  - "12"
script:
  - yarn commitlint-travis
  - yarn build
  - yarn test:once
  - cat ./coverage/core/lcov.info | ./node_modules/coveralls/bin/coveralls.js
after_success:
  - yarn travis-deploy-once "yarn semantic-release"
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
