sudo: required
language: node_js
before_install: # if "install" is overridden
  # Repo for Yarn
  - npm install yarn -g
cache:
  yarn: true
notifications:
  email: false
node_js:
  - "10"
  - "8"
before_script:
  - yarn global add @angular/cli
script:
  - yarn commitlint-travis
  - ng build core
  - ng test core --watch false
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
after_success:
  - yarn travis-deploy-once "yarn semantic-release"
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
