
sudo: required
addons:
  chrome: stable
language: node_js
before_install: # if "install" is overridden
  # Repo for Yarn
  - sudo apt-key adv --fetch-keys http://dl.yarnpkg.com/debian/pubkey.gpg
  - echo "deb http://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
  - sudo apt-get update -qq
  - sudo apt-get install -y -qq yarn
cache:
  yarn: true
notifications:
  email: false
node_js:
  - '10'
  - '8'
before_script:
  - yarn global add @angular/cli
script:
  - yarn commitlint-travis
  - ng build core
  - ng test core --browsers ChromeHeadless --watch false
after_success:
  - yarn travis-deploy-once "yarn semantic-release"
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
